(require 'init-use-package)

(when (string-equal system-type "darwin")
  (require 'init-osx))
(when (string-equal system-type "gnu/linux")
  (require 'init-linux))

(require 'init-ag)
(require 'init-color-identifiers)
(require 'init-expand-region)
(require 'init-fullframe)
(require 'init-iedit)
(require 'init-hungry-delete)
(require 'init-rainbow-delimiters)
(require 'init-smooth-scrolling)
(require 'init-spaceline)
(require 'init-themes)

(require 'init-company)
(require 'init-counsel)
(require 'init-evil)
(require 'init-flycheck)
(require 'init-magit)
(require 'init-projectile)
(require 'init-smartparens)
(require 'init-yasnippet)

(provide 'modules)
