(add-to-list 'load-path (concat user-emacs-directory "inits"))

(require 'init-cask)
(require 'init-encoding)
(require 'init-base)
(require 'init-font)
(require 'init-ibuffer)
(require 'init-dired)
(require 'init-theme)
(require 'init-smart-mode-line)
(require 'init-evil)
(require 'init-helm)
(require 'init-magit)
(require 'init-projectile)
(require 'init-multiple-cursors)
(require 'init-emmet)

(require 'init-ruby)
(require 'init-web)
(require 'init-javascript)
(require 'init-css)
(require 'init-yaml)

(require 'init-function)
