(eval-when-compile (require 'cl))

;; Package
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(add-to-list 'load-path (concat user-emacs-directory "inits"))

(require 'init-use-package)
(require 'init-encoding)
(require 'init-base)
(require 'init-osx)
(require 'init-exec-path)
(require 'init-ibuffer)
(require 'init-dired)
(require 'init-font)
(require 'init-mode-line)

(require 'init-evil)
(require 'init-emmet)
(require 'init-multiple-cursors)
(require 'init-helm)
(require 'init-magit)
(require 'init-ag)
(require 'init-ggtags)
(require 'init-projectile)
(require 'init-company)
(require 'init-smartparens)
(require 'init-quickrun)
(require 'init-rainbow-delimiters)
(require 'init-nlinum)
(require 'init-theme)

(require 'init-ruby)
(require 'init-swift)
(require 'init-web)
(require 'init-javascript)
(require 'init-css)
(require 'init-yaml)

(require 'init-function)
