(add-to-list 'load-path (expand-file-name "config" user-emacs-directory))

(require 'variable-settings)
(require 'system-settings)
(require 'general-settings)
(require 'interface-settings)

(require 'cask-settings)
(require 'theme-settings)
(require 'dired-settings)
(require 'evil-settings)
(require 'counsel-settings)
(require 'projectile-settings)
(require 'company-settings)
(require 'ag-settings)

(require 'ruby-settings)
(require 'web-settings)
(require 'javascript-settings)
(require 'css-settings)
