(require 'init-prog)
(require 'init-ruby)
(require 'init-web)
(require 'init-javascript)
(require 'init-css)
(require 'init-yaml)
(require 'init-markdown)
(require 'init-dockerfile)

(provide 'langs)
