(require 'emacs-exec-path-from-shell)
(require 'emacs-theme)
(require 'emacs-evil)
(require 'emacs-avy)
(require 'emacs-counsel)
(require 'emacs-company)
(require 'emacs-projectile)
(require 'emacs-spaceline)
(require 'emacs-quickrun)

(provide 'emacs-enhanced)
